#pragma once

#define SCREEN_THEME_WIDTH 240 // 320 // 240
#define SCREEN_THEME_HEIGHT 320 // 480 // 320
#define SCREEN_THEME_ELEM_WIDTH 200
#define SCREEN_THEME_ELEM_HEIGHT 40

#define SCREEN_THEME_COLOR                          EGA_BLACK
#define SCREEN_THEME_ELEM_COLOR                     SCREEN_THEME_COLOR
#define SCREEN_THEME_TEXT_ALIGN                     ALIGN_CENTER_CENTER
#define SCREEN_THEME_FONT_SIZE                      2
#define SCREEN_THEME_FONT_COLOR                     EGA_BRIGHT_CYAN
#define SCREEN_THEME_BORDER_THICKNESS               3
#define SCREEN_THEME_BORDER_TOP_COLOR               EGA_BRIGHT_BLUE
#define SCREEN_THEME_BORDER_LEFT_COLOR              EGA_BRIGHT_BLUE
#define SCREEN_THEME_BORDER_RIGHT_COLOR             EGA_BRIGHT_BLUE
#define SCREEN_THEME_BORDER_BOTTOM_COLOR            EGA_BRIGHT_BLUE

#define SCREEN_THEME_PUSHED_ELEM_COLOR              EGA_BRIGHT_GREEN
#define SCREEN_THEME_PUSHED_TEXT_ALIGN              SCREEN_THEME_TEXT_ALIGN
#define SCREEN_THEME_PUSHED_FONT_SIZE               SCREEN_THEME_FONT_SIZE
#define SCREEN_THEME_PUSHED_FONT_COLOR              EGA_BLACK
#define SCREEN_THEME_PUSHED_BORDER_THICKNESS        SCREEN_THEME_BORDER_THICKNESS
#define SCREEN_THEME_PUSHED_BORDER_TOP_COLOR        EGA_GREEN
#define SCREEN_THEME_PUSHED_BORDER_LEFT_COLOR       EGA_GREEN
#define SCREEN_THEME_PUSHED_BORDER_RIGHT_COLOR      EGA_GREEN
#define SCREEN_THEME_PUSHED_BORDER_BOTTOM_COLOR     EGA_GREEN

#define SCREEN_THEME_DISABLED_ELEM_COLOR            SCREEN_THEME_ELEM_COLOR
#define SCREEN_THEME_DISABLED_TEXT_ALIGN            SCREEN_THEME_TEXT_ALIGN
#define SCREEN_THEME_DISABLED_FONT_SIZE             SCREEN_THEME_FONT_SIZE
#define SCREEN_THEME_DISABLED_FONT_COLOR            EGA_DARK_GRAY
#define SCREEN_THEME_DISABLED_BORDER_THICKNESS      SCREEN_THEME_BORDER_THICKNESS
#define SCREEN_THEME_DISABLED_BORDER_TOP_COLOR      EGA_DARK_GRAY
#define SCREEN_THEME_DISABLED_BORDER_LEFT_COLOR     EGA_DARK_GRAY
#define SCREEN_THEME_DISABLED_BORDER_RIGHT_COLOR    EGA_DARK_GRAY
#define SCREEN_THEME_DISABLED_BORDER_BOTTOM_COLOR   EGA_DARK_GRAY

#define SCREEN_THEME_SLIDER_COLOR                   EGA_BRIGHT_BLUE
#define SCREEN_THEME_SLIDER_THICKNESS               8
